name: Workflow_artefato_Exercicio_Leandro

on:
  push:
  
env:
  VARIAVEL_1: LEANDRO
  VARIAVEL_2: SAO PAULO

jobs:

  checkout_code:
    name: Faz checkout do codigo
    runs-on: ubuntu-latest
    env:
      VARIAVEL_JOB: 33
      
    steps:
    - name: Checkout reposit√≥rio
      uses: actions/checkout@v3.3.0
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ vars.NOME }}
        path: .
